name: 'ga4_analytics'
version: '1.0.0'
config-version: 2

# profiles.yml の最上位キーと一致させる
profile: 'ga4_analytics'

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ga4_analytics:
    staging:
      +materialized: view
    mart:
      +materialized: table
